name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  test:
    name: Test and checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust toolchain
        run: |
          rustup set profile minimal
          rustup toolchain install stable -c "clippy,rustfmt"
          rustup default stable
      - name: Ensure cargo fmt has been run
        run: cargo fmt --check
      - name: Run clippy
        run: cargo clippy --all-targets --all-features
      - name: Run tests with all features
        run: cargo test --all-features
      - name: Check default
        run: cargo check --features
      - name: check no features
        run: cargo check --no-default-features
      - name: check alloc only
        run: cargo check --no-default-features --features alloc

